"""Diplomacy module unit + property tests.

Covers the 7-bloc constants, water-filling shock distribution, combined damping
bounds, deterministic campaign behavior, Monte Carlo distribution shape, and
the Mulberry32 RNG parity against a golden sequence generated from the JS
reference implementation.

The behavioral parity test against the JS playground (test_js_python_behavioral_parity)
belongs in Phase 5 (integration), not Phase 4. It requires Agent A's microgrid_sim.js
to exist; it is intentionally omitted here.
"""

from __future__ import annotations

import copy

import pytest
from hypothesis import given, settings, strategies as st

from electicity_model.diplomacy import (
    BLOCS,
    BLOC_REL,
    SHOCK_BASE_PROB,
    SHOCK_NAMES,
    SOVEREIGNTY_MAX,
    Mulberry32,
    combined_damping,
    diplomacy_hash,
    monte_carlo,
    pairwise_adjustment,
    pick_shock,
    shock_distribution,
    simulate_campaign,
    sovereignty_spent,
)


BLOC_NAMES = sorted(BLOCS.keys())
NON_BAU_SHOCKS = tuple(s for s in SHOCK_NAMES if s != "bau")


# ---------------------------------------------------------------------------
# Constants and structure
# ---------------------------------------------------------------------------


def test_blocs_complete():
    assert len(BLOCS) == 7
    for name, b in BLOCS.items():
        assert b.name == name
        assert b.label
        assert b.cost > 0
        assert b.sovereignty in {1, 2}


def test_relationship_matrix_canonical_order():
    for (a, b) in BLOC_REL.keys():
        assert a < b, f"BLOC_REL key ({a},{b}) is not in canonical alphabetical order"


def test_shock_base_prob_has_bau():
    assert "bau" in SHOCK_BASE_PROB
    # All known supply shocks present.
    for name in ("ir_shortage", "li_shortage", "china_decoupling", "maritime_blockade"):
        assert name in SHOCK_BASE_PROB


def test_diplomacy_hash_stable_and_short():
    h = diplomacy_hash()
    assert len(h) == 12
    assert h == diplomacy_hash()


# ---------------------------------------------------------------------------
# shock_distribution
# ---------------------------------------------------------------------------


def test_shock_distribution_normalizes_empty_posture():
    d = shock_distribution(frozenset())
    assert sum(d.values()) == pytest.approx(1.0, abs=1e-9)
    for v in d.values():
        assert 0.0 <= v <= 0.5 + 1e-9


def test_shock_distribution_pathological_posture_clamps_to_half():
    # All 7 blocs (would exceed sovereignty cap, but we bypass the cap here
    # because shock_distribution itself does not enforce it).
    posture = frozenset(BLOC_NAMES)
    d = shock_distribution(posture)
    assert sum(d.values()) == pytest.approx(1.0, abs=1e-9)
    for v in d.values():
        assert v <= 0.5 + 1e-9


# ---------------------------------------------------------------------------
# combined_damping
# ---------------------------------------------------------------------------


def test_combined_damping_with_bau_returns_one():
    for posture in [frozenset(), frozenset({"WEST_FRIEND"}), frozenset({"WEST_FRIEND", "EU_FRIEND"})]:
        assert combined_damping("bau", posture) == 1.0


def test_combined_damping_bounds_single_and_pair():
    # sample a few postures; must always be in [0, 1].
    samples = [
        frozenset(),
        frozenset({"WEST_FRIEND"}),
        frozenset({"EAST_FRIEND"}),
        frozenset({"WEST_FRIEND", "EU_FRIEND"}),
        frozenset({"WEST_FRIEND", "EAST_FRIEND"}),  # friction
        frozenset({"AFRICA_FRIEND", "EU_FRIEND"}),  # synergy
    ]
    for posture in samples:
        for shock in NON_BAU_SHOCKS:
            d = combined_damping(shock, posture)
            assert 0.0 <= d <= 1.0, f"out of range for {shock} {posture}: {d}"


def test_relationship_clamp_extremes():
    # Positive synergy posture; pairwise sum positive. Multiplier <= 1.5.
    pos = frozenset({"AFRICA_FRIEND", "EU_FRIEND", "NORTH_FRIEND", "LATAM_FRIEND", "WEST_FRIEND"})
    assert pairwise_adjustment(pos) <= 1.5 + 1e-9
    # Friction-heavy: WEST + EAST + EU.
    neg = frozenset({"WEST_FRIEND", "EAST_FRIEND", "EU_FRIEND"})
    adj = pairwise_adjustment(neg)
    assert 0.3 <= adj <= 1.5


# ---------------------------------------------------------------------------
# Mulberry32 parity against JS golden sequence
# ---------------------------------------------------------------------------


# Generated by:
#   node -e "function m(seed){let a=seed>>>0; return ()=>{a=(a+0x6D2B79F5)>>>0; let t=a; \
#       t=Math.imul(t^(t>>>15),t|1); t^=t+Math.imul(t^(t>>>7),t|61); \
#       return ((t^(t>>>14))>>>0)/4294967296;}}; const r=m(42); for(let i=0;i<8;i++) console.log(r());"
MULBERRY32_GOLDEN_SEED_42: list[float] = [
    0.6011037519201636,
    0.44829055899754167,
    0.8524657934904099,
    0.6697340414393693,
    0.17481389874592423,
    0.5265925421845168,
    0.2732279943302274,
    0.6247446539346129,
]


def test_mulberry32_parity():
    rng = Mulberry32(42)
    out = [rng.next_float() for _ in range(8)]
    for got, want in zip(out, MULBERRY32_GOLDEN_SEED_42, strict=True):
        assert got == pytest.approx(want, rel=0, abs=1e-15), (got, want)


def test_pick_shock_uses_full_distribution():
    # With all-mass at one shock, pick_shock returns it.
    only_bau = {name: (1.0 if name == "bau" else 0.0) for name in SHOCK_NAMES}
    rng = Mulberry32(0)
    for _ in range(20):
        assert pick_shock(only_bau, rng) == "bau"


# ---------------------------------------------------------------------------
# simulate_campaign
# ---------------------------------------------------------------------------


def test_simulate_deterministic_with_seed():
    posture = ["WEST_FRIEND", "LATAM_FRIEND"]
    a = simulate_campaign(posture, seed=7, years=4)
    b = simulate_campaign(posture, seed=7, years=4)
    assert a == b


def test_simulate_campaign_does_not_mutate_inputs():
    posture = ["WEST_FRIEND", "LATAM_FRIEND"]
    snapshot = copy.deepcopy(posture)
    _ = simulate_campaign(posture, seed=3, years=3)
    assert posture == snapshot


def test_unknown_bloc_raises():
    with pytest.raises(ValueError, match="unknown bloc"):
        simulate_campaign(["ATLANTIS_FRIEND"], seed=0, years=2)


def test_sovereignty_overflow_raises():
    # All 7 = 1+1+2+2+1+2+1 = 10, at the cap.
    full = list(BLOC_NAMES)
    spent = sovereignty_spent(frozenset(full))
    assert spent == SOVEREIGNTY_MAX
    # Build a synthetic over-cap posture by listing one bloc twice. The frozenset
    # collapses duplicates, so instead: pick a posture whose sovereignty exceeds 10.
    # Since sum of all blocs is exactly 10, we cannot construct an over-cap posture
    # from the 7 valid blocs alone. Verify the cap is at-the-limit acceptable:
    _ = simulate_campaign(full, seed=0, years=1)


def test_bloc_bonus_applies_under_bau():
    """A WEST_FRIEND posture (PTC rebate) should produce strictly lower year-1 capex
    than an empty posture under bau, because the rebate exceeds the bloc fee."""
    # Year 1 only, run a 1-year campaign with seed that draws bau (drawn from dist).
    # Easier path: directly compare monte_carlo means under all-bau-weighted draw.
    # Just compare simulated single year via simulate_campaign over many seeds.
    west_capex_total = 0.0
    empty_capex_total = 0.0
    n = 30
    for s in range(n):
        rw = simulate_campaign(["WEST_FRIEND"], seed=s, years=1)
        re = simulate_campaign([], seed=s, years=1)
        # Only count years where shock == bau in BOTH (so we compare apples to apples).
        if rw.years[0].shock == "bau" and re.years[0].shock == "bau":
            west_capex_total += rw.years[0].capex_total
            empty_capex_total += re.years[0].capex_total
    # If we got at least a few matched bau years, WEST should be strictly cheaper.
    assert west_capex_total > 0.0  # at least some matched
    assert west_capex_total < empty_capex_total


# ---------------------------------------------------------------------------
# Monte Carlo
# ---------------------------------------------------------------------------


def test_monte_carlo_distribution_shape():
    s = monte_carlo(["WEST_FRIEND", "LATAM_FRIEND"], runs=200, seed=11)
    assert s.runs == 200
    # Non-degenerate: p10 <= p50 <= p90, std > 0.
    assert s.p10 <= s.p50 <= s.p90
    assert s.std > 0.0


def test_friends_union_helps_under_shock():
    """Three well-matched blocs > no blocs at the same seed (median).

    The 'helped' posture is chosen for shock-coverage breadth:
    EAST_FRIEND covers china_decoupling/maritime/li/pt; AFRICA_FRIEND covers
    ir/pt; SOUTH_CENTRAL_FRIEND covers li/maritime/regional_autarky. With at
    least three blocs, the Friends Union umbrella (0.75) also kicks in.
    """
    empty = monte_carlo([], runs=200, seed=42)
    helped = monte_carlo(
        ["EAST_FRIEND", "AFRICA_FRIEND", "SOUTH_CENTRAL_FRIEND"], runs=200, seed=42
    )
    assert helped.p50 > empty.p50


def test_friction_pair_hurts():
    """WEST+EAST friction reduces median below just WEST under default mix."""
    just_west = monte_carlo(["WEST_FRIEND"], runs=300, seed=99)
    west_east = monte_carlo(["WEST_FRIEND", "EAST_FRIEND"], runs=300, seed=99)
    assert west_east.p50 < just_west.p50


# ---------------------------------------------------------------------------
# Hypothesis property tests
# ---------------------------------------------------------------------------


_posture_strategy = st.sets(st.sampled_from(BLOC_NAMES), max_size=4).map(frozenset)
_shock_strategy = st.sampled_from(SHOCK_NAMES)


@given(posture=_posture_strategy, shock=_shock_strategy)
@settings(max_examples=80, deadline=None)
def test_property_combined_damping_in_unit_interval(
    posture: frozenset[str], shock: str,
) -> None:
    if sovereignty_spent(posture) > SOVEREIGNTY_MAX:
        return
    d = combined_damping(shock, posture)
    assert 0.0 <= d <= 1.0


@given(posture=_posture_strategy)
@settings(max_examples=50, deadline=None)
def test_property_shock_distribution_normalized_and_clamped(
    posture: frozenset[str],
) -> None:
    d = shock_distribution(posture)
    assert sum(d.values()) == pytest.approx(1.0, abs=1e-9)
    for v in d.values():
        assert -1e-12 <= v <= 0.5 + 1e-9


@given(seed=st.integers(min_value=0, max_value=10_000))
@settings(max_examples=20, deadline=None)
def test_property_simulate_campaign_deterministic(seed: int) -> None:
    posture = ["WEST_FRIEND", "LATAM_FRIEND"]
    a = simulate_campaign(posture, seed=seed, years=3)
    b = simulate_campaign(posture, seed=seed, years=3)
    assert a.total_score == b.total_score
    assert tuple(yr.shock for yr in a.years) == tuple(yr.shock for yr in b.years)


# ---------------------------------------------------------------------------
# Phase 5: behavioral parity vs the JS playground
# ---------------------------------------------------------------------------


import json
import shutil
import subprocess
from pathlib import Path


_PARITY_HARNESS = Path(__file__).parent / "_js_parity_harness.js"
_NODE_BIN = shutil.which("node")


@pytest.mark.skipif(_NODE_BIN is None, reason="node not available; behavioral parity test skipped")
def test_js_python_behavioral_parity(tmp_path):
    """JS playground and Python diplomacy module produce identical numerics
    for a fixture of math-kernel calls: Mulberry32 sequences, combined_damping,
    and shock_distribution. Tolerance 1e-9 (these are deterministic floats)."""
    fixtures = {
        "mulberry32": [
            {"seed": 42, "n": 8},
            {"seed": 1, "n": 4},
            {"seed": 0, "n": 4},
        ],
        "combined_damping": [
            {"shock": "bau", "posture": [], "trust": None},
            {"shock": "china_decoupling", "posture": ["EAST_FRIEND"], "trust": None},
            {"shock": "pt_shortage", "posture": ["AFRICA_FRIEND", "NORTH_FRIEND"], "trust": None},
            {"shock": "li_shortage", "posture": ["LATAM_FRIEND", "SOUTH_CENTRAL_FRIEND"], "trust": None},
            {"shock": "maritime_blockade", "posture": ["EAST_FRIEND", "SOUTH_CENTRAL_FRIEND", "AFRICA_FRIEND"], "trust": None},
        ],
        "shock_distribution": [
            {"posture": []},
            {"posture": ["WEST_FRIEND"]},
            {"posture": ["EAST_FRIEND", "AFRICA_FRIEND"]},
            {"posture": ["EU_FRIEND", "LATAM_FRIEND", "AFRICA_FRIEND"]},
        ],
    }
    fixture_path = tmp_path / "fixtures.json"
    fixture_path.write_text(json.dumps(fixtures))
    proc = subprocess.run(
        [str(_NODE_BIN), str(_PARITY_HARNESS), str(fixture_path)],
        capture_output=True,
        text=True,
        timeout=30,
    )
    assert proc.returncode == 0, f"harness failed: {proc.stderr}"
    js_out = json.loads(proc.stdout)

    # 1. Mulberry32 sequence parity
    for fx, js_seq in zip(fixtures["mulberry32"], js_out["mulberry32"]):
        rng = Mulberry32(fx["seed"])
        py_seq = [rng.next_float() for _ in range(fx["n"])]
        assert len(py_seq) == len(js_seq)
        for j, p in zip(js_seq, py_seq):
            assert abs(j - p) < 1e-12, f"Mulberry32 seed={fx['seed']} mismatch: js={j} py={p}"

    # 2. combined_damping parity
    for fx, js_val in zip(fixtures["combined_damping"], js_out["combined_damping"]):
        py_val = combined_damping(fx["shock"], frozenset(fx["posture"]))
        assert abs(js_val - py_val) < 1e-9, (
            f"combined_damping({fx['shock']!r}, {fx['posture']!r}) "
            f"mismatch: js={js_val} py={py_val}"
        )

    # 3. shock_distribution parity
    for fx, js_dist in zip(fixtures["shock_distribution"], js_out["shock_distribution"]):
        py_dist = shock_distribution(frozenset(fx["posture"]))
        assert set(js_dist) == set(py_dist), "shock keys differ"
        for k in py_dist:
            assert abs(js_dist[k] - py_dist[k]) < 1e-9, (
                f"shock_distribution({fx['posture']!r})[{k}] "
                f"mismatch: js={js_dist[k]} py={py_dist[k]}"
            )
